[tool.poetry]
name = "a2sum"
version = "0.1.0"
description = ""
authors = ["George Padron <georgenpadron@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
speechbrain = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
